version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: secure-exam-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: secure_exam
      POSTGRES_PASSWORD: secure_exam_pass
      POSTGRES_DB: secure_exam
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
